name: autofix.ci
on:
  pull_request:
  push:
permissions: {}
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
      - run: |
          npm install
          npx prettier . --write
      - uses: autofix-ci/action@v1
        with:
          commit-message: "Apply Prettier format"
      - name: Lint with Prettier and ESLint
        run: npm run lint